name: Update Followers

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures
  push:
    branches:
      - main

jobs:
  update-followers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install jq and curl
      run: sudo apt-get install jq curl

    - name: Fetch followers and update README
      run: |
        # Récupérer les followers
        followers=$(curl -s https://api.github.com/users/oda-alexandre/followers)
        
        # Extraire les noms d'utilisateur des followers
        usernames=$(echo $followers | jq -r '.[].login')
        
        # Créer la liste formatée pour le README
        output="## Followers\n\n"
        for username in $usernames; do
          # Vérifier si l'utilisateur a une image de profil personnalisée
          response=$(curl -s -o /dev/null -w "%{http_code}" https://github.com/$username.png)
          if [ "$response" = "200" ]; then
            image_url="https://github.com/$username.png?size=50"
          else
            # Utiliser une image de remplacement si pas d'image personnalisée
            image_url="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          fi
          output+="<a href=\"https://github.com/$username\"><img src=\"$image_url\" width=\"50px\" height=\"50px\" alt=\"$username\"></a> "
        done
        
        # Mettre à jour le README
        sed -i '/<!-- TOP-FOLLOWERS:START -->/,/<!-- TOP-FOLLOWERS:END -->/c\<!-- TOP-FOLLOWERS:START -->\n'"$output"'\n<!-- TOP-FOLLOWERS:END -->' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update followers list' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
