name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitHub User Info
        id: userinfo
        run: |
          USER_INFO=$(curl -s https://api.github.com/users/oda-alexandre)
          NAME=$(echo "$USER_INFO" | jq -r '.name')
          LOGIN=$(echo "$USER_INFO" | jq -r '.login')
          BIO=$(echo "$USER_INFO" | jq -r '.bio')
          echo "::set-output name=name::$NAME"
          echo "::set-output name=login::$LOGIN"
          echo "::set-output name=bio::$BIO"

      # - name: Update README with User Info
      #   run: |
      #     NAME="${{ steps.userinfo.outputs.name }}"
      #     LOGIN="${{ steps.userinfo.outputs.login }}"
      #     BIO="${{ steps.userinfo.outputs.bio }}"
      #     sed -i.bak -e "/<!-- NAME-START -->/,/<!-- NAME-END -->/{s/<!-- NAME-START -->.*<!-- NAME-END -->/<!-- NAME-START -->$NAME<!-- NAME-END -->/}" README.md
      #     sed -i.bak -e "/<!-- LOGIN-START -->/,/<!-- LOGIN-END -->/{s/<!-- LOGIN-START -->.*<!-- LOGIN-END -->/<!-- LOGIN-START -->@$LOGIN<!-- LOGIN-END -->/}" README.md
      #     sed -i.bak "/<!-- ABOUT-ME:START -->/,/<!-- ABOUT-ME:END -->/{//!d;}" README.md
      #     echo "$BIO" | sed 's/^/ /' | sed -i "/<!-- ABOUT-ME:START -->/r /dev/stdin" README.md

      # - name: Update Blog Posts
      #   uses: gautamkrishnar/blog-post-workflow@master
      #   with:
      #     max_post_count: '4'
      #     feed_list: 'https://www.oda-alexandre.com/blog/feed'

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
        run: |
          const { Octokit } = require("@octokit/rest");
          const fs = require('fs');
          
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          
          async function getFollowers() {
            const followers = await octokit.paginate(octokit.users.listFollowersForUser, {
              username: 'VotreNomUtilisateur'
            });
            return followers;
          }
          
          async function updateReadme() {
            const followers = await getFollowers();
            const followerList = followers.map(follower => `- [${follower.login}](${follower.html_url})`).join('\n');
            
            const readmeContent = fs.readFileSync('README.md', 'utf8');
            const updatedContent = readmeContent.replace(
              /<!-- FOLLOWERS-LIST:START -->[\s\S]*<!-- FOLLOWERS-LIST:END -->/,
              `<!-- FOLLOWERS-LIST:START -->\n${followerList}\n<!-- FOLLOWERS-LIST:END -->`
            );
            
            fs.writeFileSync('README.md', updatedContent);
          }
          
          updateReadme();

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest information"
          git push
