name: Update README with Followers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Met à jour chaque heure

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install @octokit/rest

    - name: Update README with followers
      env:
        README_TOKEN: ${{ secrets.README_TOKEN }}
      run: |
        node -e "
          const { Octokit } = require('@octokit/rest');
          const fs = require('fs');

          const octokit = new Octokit({ auth: process.env.README_TOKEN });

          async function getFollowers() {
            const followers = await octokit.paginate(octokit.users.listFollowersForUser, {
              username: process.env.GITHUB_REPOSITORY_OWNER
            });
            return followers;
          }

          async function updateReadme() {
            const followers = await getFollowers();
            const followerList = followers.map(follower => \`- [\${follower.login}](\${follower.html_url})\`).join('\n');

            const readmeContent = fs.readFileSync('README.md', 'utf8');
            const updatedContent = readmeContent.replace(
              /<!--ACTION_START_FLAG:github-followers-->[\\s\\S]*<!--ACTION_END_FLAG:github-followers-->/,
              \`<!--ACTION_START_FLAG:github-followers-->\n\${followerList}\n<!--ACTION_END_FLAG:github-followers-->\`
            );

            fs.writeFileSync('README.md', updatedContent);
          }

          updateReadme();
        "

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet || git commit -m "Update README with latest followers"
        git push
