name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitHub User Info
        id: userinfo
        run: |
          USER_INFO=$(curl -s https://api.github.com/users/oda-alexandre)
          NAME=$(echo "$USER_INFO" | jq -r '.name')
          BIO=$(echo "$USER_INFO" | jq -r '.bio')
          echo "::set-output name=name::$NAME"
          echo "::set-output name=bio::$BIO"

      - name: Update README with User Info
        run: |
          NAME="${{ steps.userinfo.outputs.name }}"
          BIO="${{ steps.userinfo.outputs.bio }}"
          sed -i -e "/<!-- NAME-START -->/,/<!-- NAME-END -->/{s/<!-- NAME-START -->.*<!-- NAME-END -->/<!-- NAME-START -->$NAME<!-- NAME-END -->/}" README.md
          sed -i "/<!-- ABOUT-ME:START -->/,/<!-- ABOUT-ME:END -->/{//!d;}" README.md
          echo "$BIO" | sed 's/^/ /' | sed -i "/<!-- ABOUT-ME:START -->/r /dev/stdin" README.md

      - name: Fetch and Update Followers
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/oda-alexandre/followers)
          FOLLOWER_CARDS=""
          for row in $(echo "${FOLLOWERS}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            LOGIN=$(_jq '.login')
            FOLLOWER_CARDS="$FOLLOWER_CARDS[![$LOGIN](https://img.shields.io/github/followers/$LOGIN?label=$LOGIN&style=for-the-badge&logo=github&logoColor=white&labelColor=0A66C2&color=0A66C2)](https://github.com/$LOGIN) "
          done
          sed -i "/<!-- TOP-FOLLOWERS:START -->/,/<!-- TOP-FOLLOWERS:END -->/{//!d;}" README.md
          echo "<div style=\"display: flex; flex-wrap: wrap; gap: 5px;\">" >> README.md
          echo "$FOLLOWER_CARDS" | sed -i "/<!-- TOP-FOLLOWERS:START -->/r /dev/stdin" README.md
          echo "</div>" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest information"
          git push
