name: Update README with Followers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Met à jour chaque heure

jobs:
  github_followers_job:
    runs-on: ubuntu-latest
    name: A job to display GitHub followers in your profile
    steps:
      - uses: actions/checkout@v3

      - name: Use github-followers-action to update README.md
        id: github-follower
        uses: JieDing/github-followers-action@main
        env:
          LOGIN: ${{ github.repository_owner }}
          PAT: ${{ secrets.README_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet || git commit -m "Update README with latest followers"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.README_TOKEN }}
          branch: ${{ github.ref }}
