name: Update Followers

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures
  push:
    branches:
      - main

jobs:
  update-followers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install jq
      run: sudo apt-get install jq

    - name: Fetch followers and update README
      run: |
        # Récupérer les followers
        followers=$(curl -s https://api.github.com/users/oda-alexandre/followers)
        
        # Extraire les noms d'utilisateur des followers
        usernames=$(echo $followers | jq -r '.[].login')
        
        # Créer la liste formatée pour le README
        output="# Mes Followers\n\n"
        for username in $usernames; do
          output+="- [$username](https://github.com/$username)\n"
        done
        
        # Écrire dans le README
        echo -e "$output" > FOLLOWERS.md

        # Mettre à jour le README principal
        sed -i '/<!-- FOLLOWERS_START -->/,/<!-- FOLLOWERS_END -->/c\<!-- FOLLOWERS_START -->\n'"$output"'\n<!-- FOLLOWERS_END -->' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update followers list'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
