name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitHub User Info
        id: userinfo
        run: |
          USER_INFO=$(curl -s https://api.github.com/users/oda-alexandre)
          NAME=$(echo "$USER_INFO" | jq -r '.name')
          LOGIN=$(echo "$USER_INFO" | jq -r '.login')
          BIO=$(echo "$USER_INFO" | jq -r '.bio')
          echo "::set-output name=name::$NAME"
          echo "::set-output name=login::$LOGIN"
          echo "::set-output name=bio::$BIO"

      # - name: Update README with User Info
      #   run: |
      #     NAME="${{ steps.userinfo.outputs.name }}"
      #     LOGIN="${{ steps.userinfo.outputs.login }}"
      #     BIO="${{ steps.userinfo.outputs.bio }}"
      #     sed -i.bak -e "/<!-- NAME-START -->/,/<!-- NAME-END -->/{s/<!-- NAME-START -->.*<!-- NAME-END -->/<!-- NAME-START -->$NAME<!-- NAME-END -->/}" README.md
      #     sed -i.bak -e "/<!-- LOGIN-START -->/,/<!-- LOGIN-END -->/{s/<!-- LOGIN-START -->.*<!-- LOGIN-END -->/<!-- LOGIN-START -->@$LOGIN<!-- LOGIN-END -->/}" README.md
      #     sed -i.bak "/<!-- ABOUT-ME:START -->/,/<!-- ABOUT-ME:END -->/{//!d;}" README.md
      #     echo "$BIO" | sed 's/^/ /' | sed -i "/<!-- ABOUT-ME:START -->/r /dev/stdin" README.md

      # - name: Update Blog Posts
      #   uses: gautamkrishnar/blog-post-workflow@master
      #   with:
      #     max_post_count: '4'
      #     feed_list: 'https://www.oda-alexandre.com/blog/feed'

      - name: Fetch and Update Followers
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/oda-alexandre/followers)
          FOLLOWER_CARDS=""
          for row in $(echo "${FOLLOWERS}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            LOGIN=$(_jq '.login')
            AVATAR_URL=$(_jq '.avatar_url')
            FOLLOWER_CARDS="$FOLLOWER_CARDS<div style=\"display: inline-block; text-align: center; margin: 10px;\"><a href=\"https://github.com/$LOGIN\" target=\"_blank\"><img src=\"$AVATAR_URL\" alt=\"$LOGIN\" style=\"width: 100px; height: 100px; border-radius: 50%; object-fit: cover;\"><br>@$LOGIN</a></div>"
          done
          sed -i "/<!-- TOP-FOLLOWERS:START -->/,/<!-- TOP-FOLLOWERS:END -->/{//!d;}" README.md
          echo "$FOLLOWER_CARDS" | sed -i "/<!-- TOP-FOLLOWERS:START -->/r /dev/stdin" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest information"
          git push
