name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update GitHub Profile README
        uses: theboi/github-update-readme@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "Bonjour, je suis ODA ALEXANDRE"
          subhead: |
            ```markdown
            ### @MAITRE_ODA
            #### DEVSECOPS || ÉTHICAL HACKER
            ```
          footer: "**Retrouvez-moi sur [LinkedIn](https://www.linkedin.com/signup/public-profile-join?vieweeVanityName=oda-alexandre&trk=public_profile_top-card-primary-button-join-to-connect).**"

      - name: Fetch and Update Bio
        run: |
          BIO=$(curl -s https://api.github.com/users/oda-alexandre | jq -r '.bio')
          sed -i.bak "/<!-- ABOUT-ME:START -->/,/<!-- ABOUT-ME:END -->/{//!d;}" README.md
          sed -i "/<!-- ABOUT-ME:START -->/a $BIO" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest information"
          git push
