name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch GitHub Bio
        id: bio
        run: |
          BIO=$(curl -s https://api.github.com/users/oda-alexandre | jq -r '.bio')
          echo "::set-output name=bio::$BIO"

      - name: Update README with Bio
        run: |
          sed -i.bak "/<!-- ABOUT-ME:START -->/,/<!-- ABOUT-ME:END -->/{//!d;}" README.md
          sed -i "/<!-- ABOUT-ME:START -->/a $(echo "${{ steps.bio.outputs.bio }}")" README.md

      # - name: Update Blog Posts
      #   uses: gautamkrishnar/blog-post-workflow@master
      #   with:
      #     feed_list: "https://www.oda-alexandre.com/blog/feed"

      - name: Update Top Followers
        run: |
          TOP_FOLLOWERS=$(curl -s https://api.github.com/users/oda-alexandre/followers | jq -r '.[].login' | head -n 5)
          FOLLOWERS_MARKDOWN=$(echo "$TOP_FOLLOWERS" | awk '{print "- " $1}')
          FOLLOWERS_MARKDOWN=$(echo "$FOLLOWERS_MARKDOWN" | sed ':a;N;$!ba;s/\n/\\n/g')
          sed -i.bak "/<!-- TOP-FOLLOWERS:START -->/,/<!-- TOP-FOLLOWERS:END -->/{//!d;}" README.md
          sed -i "/<!-- TOP-FOLLOWERS:START -->/a $FOLLOWERS_MARKDOWN" README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest information"
          git push
